typography_spectrum: 0.4818296
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#8a5b8f'
    - '#fbb466'
    - '#7db2e4'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: DansTestSite
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: RCLA.co.uk
description: For the very best in training
purpose: []
