name: DansTestSite
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4818296
title: Test of the Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#8a5b8f'
    - '#fbb466'
    - '#7db2e4'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
