name: DansTestSite
favicon: null
layout_spectrum: 0.8515037
typography_spectrum: 0.4818296
title: Test of the Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#979797'
    - '#231F20'
    - '#EF1A24'
    - '#BFBFBF'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
