typography_spectrum: 0.025146557483822107
color:
  brandColors:
    - '#FBF9FA'
    - '#B01E86'
    - '#E57516'
    - '#A2C800'
    - '#C4C4C4'
  brandStrength: 0.5921725395601243
  lightness: 0.7073553958907723
  saturation: 0.7137777423486114
  rhythmicContrast: 0.5692961132153869
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7307872197125107
analytics:
  google: null
  facebook: null
  twitter: null
name: DansTestSite
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: RCLA.co.uk
description: For the very best in training
purpose: []
