typography_spectrum: 0.13270667870528996
color:
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
  brandStrength: 0.8998156785964966
  lightness: 0.6250712496694177
  saturation: 0.09802104346454144
  rhythmicContrast: 0.24182317475788295
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7860312422271818
analytics:
  google: null
  facebook: null
  twitter: null
name: DansTestSite
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: RCLA.co.uk
description: For the very best in training
purpose: []
